<?php
/**
* @file
* A description of what your module does.
*/

/**
 * Implements hook_page_attachments().
 */
function rir_notifier_page_attachments(array &$attachments) {
  if (Drupal::currentUser()->isAnonymous()){
    $attachments['#attached']['library'][] = 'rir_notifier/rir_scripts';
    $attachments['#attached']['library'][] = 'core/drupal.dialog.ajax';
  }
}

/**
 * Implements hook_theme().
 */
function rir_notifier_theme($existing, $type, $theme, $path) {

  return [
    'rir_subscribe_search' => [
      'variables' => [
        'button' => t('Subscribe'),
      ]
    ]
  ];
}