<?php
/**
* @file
* A description of what your module does.
*/

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_page_attachments().
 */
function rir_notifier_page_attachments(array &$attachments) {
  if (Drupal::currentUser()->isAnonymous()){
    $attachments['#attached']['library'][] = 'rir_notifier/rir_scripts';
    $attachments['#attached']['library'][] = 'core/drupal.dialog.ajax';
  }
}

/**
 * Implements hook_theme().
 */
function rir_notifier_theme($existing, $type, $theme, $path) {

  return [
    'rir_subscribe_search' => [
      'variables' => [
        'button' => t('Subscribe'),
      ]
    ]
  ];
}

/**
 * Implements hook_form_alter().
 */
function rir_notifier_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'views-exposed-form'){

  }
}

/**
 * Implements hook_views_plugins_exposed_form_alter().
 */
function rir_notifier_views_plugins_exposed_form_alter(array &$plugins) {
  kint($plugins);
  die();
}